name: Example 1

on:
  push:
    branches: 
    - main
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: |
        echo "Branch name is: ${{ github.ref_name }}" >> summary.txt

  job2:
    runs-on: [self-hosted, Linux, X64, docker]
    steps:
    - name: Check summary file
      run: |
        if [[ -f summary.txt ]]; then
          echo "exists"
        else
          echo "not found"
          exit 1
        fi
