name: Example 1

on:
  push:
    branches: 
    - main
    branches-ignore: 
    - test*
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Show branch name
      run: |
        
        echo "Branch name is: ${{ github.ref_name }}"
