name: Example 1

on:
  push:
    branches: 
    - main
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: |
        echo "::debug ::Create a summary file"
        echo ": ${{ github.sha }}" >> summary.txt

    - uses: actions/upload-artifact@v3
      with:
        name: summary
        path: |
          summary.txt

  job2:
    needs: 
    - job1
    runs-on: [self-hosted, Linux, X64, docker]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: summary

    - name: Check summary file
      run: |
        echo "::warning ::Checking summary file"
        if [[ -f summary.txt ]]; then
          echo "::notice title=Commit SHA::$(cat summary.txt)"
        else
          echo "::error ::File not found"
          exit 1
        fi
