name: Example 1

concurrency: 
  group: ci
  cancel-in-progress: true
    

on:
  push:
    branches: 
    - main
    
  workflow_dispatch:
    
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Build 2
      run: |
        sleep 60
