name: Example 1

on:
  push:
    branches: 
    - main
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

#    - run: |
#        echo "::debug ::Create a summary file"
#        echo ": ${{ github.sha }}" >> summary.txt
    - name: Set custom outputs
      id: set-custom-outputs
      run: |
        echo "commit-sha=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Show outputs
      run: |
        echo "::notice title=Commit SHA::${{ steps.set-custom-outputs.outputs.commit-sha }}"

    - uses: actions/upload-artifact@v3
      with:
        name: summary
        path: |
          summary.txt
        retention-days: 1

  job2:
    needs: 
    - job1
    runs-on: [self-hosted, Linux, X64, docker]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: summary

    - name: Check summary file
      run: |
        echo "::warning ::Checking summary file"
        if [[ -f summary.txt ]]; then
          echo "::notice title=Commit SHA::$(cat summary.txt)"
        else
          echo "::error ::File not found"
          exit 1
        fi
